name: Help
description: Please file an issue in our help repo.
title: "[Help] "
labels: [question]
body:
- type: textarea
  attributes:
    label: What do you need help with?
    description: |
      If you have a question about Arisen Studio that is not a bug report or feature request, please post it in https://github.com/ohhsodead/arisen-studio/issues/new/choose
      
      Please clearly explain what exactly you need help with.
  validations:
    required: true
- type: 
